# Initial number of species places on the grid, as a fraction of the total number of locations on the grid.
# E.g., a 10x10 grid (100 locations) with NUM_INITIAL_SPECIES_FRACTION=0.2 means 20 species are placed on the grid 
NUM_INITIAL_SPECIES_FRACTION: 0.2

# Number of moving and feeding actions made per day 
NUM_ACTIONS_PER_DAY: 30

# Controls the probability of food being generated at a given location 
FOOD_PROBABILITY_SCALAR: 0.1
FOOD_PROBABILITY_STD: 10

# The temperature in which the most food is produced 
OPTIMAL_TEMPERATURE: 10

# @Atreyi: to explain 
SPEED_MODIFIER: 10

# Initial energy of a species during *initial* population (not during reproduction) (@Atreyi to check)
INITIAL_ENERGY: 5

# Initial trait values 
INITIAL_SIZE: 1
INITIAL_SPEED: 1
INITIAL_VISION: 1
INITIAL_AGGRESSION: 1

# The amount of energy gained by eating each piece of food (@Atreyi to check)
FOOD_VALUE: 1 